apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-service
        image: lbatalla/backend_service:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-gtw
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: be-svc
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: be-svc
  labels:
    app: be-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: backend