apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: lbatalla/frontend_service:stable # repositorio example ACR 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_ENDPOINT
          value: http://127.0.0.1:80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  labels:
    app: fe-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: frontend-service